export enum SKILLS {
  REACT = "React",
  REACT_NATIVE = "React Native",
  TYPESCRIPT = "Typescript",
  MAGENTO = "Magento",
  PWA_STUDIO = "PWA Studio",
  NEXT_JS = "NextJS",
  TALWIND = "Tailwind CSS",
  FIREBASE = "Firebase",
  GRAPHQL = "GraphQL",
  NEW_RELIC = "New Relic",
  GA = "Google Analytics",
  GTM = "Google Tag Manager",
  APP_STORE_DEPLOY = "App Store",
  PLAY_STORE_DEPLOY = "Google Play",
  MICROSERVICES = "Microservices",
  REST = "RESTfull API",
  STYLED_COMPONENTS = "Styled Components",
  CI_CD = "CI/CD",
  NODE = "Node.js",
  REDUX = "Redux",
  JAVA = "Java",
  MOBX = "MobX",
  CAMERA = "Camera interaction",
  GPS_TRACKING = "GPS tracking",
  NATIVE_MODULES = "Native modules",
  PUSH_NOTIFICATION = "Push notifications"
}
