export enum SKILLS {
  REACT = "React",
  REACT_NATIVE = "React Native",
  TYPESCRIPT = "Typescript",
  MAGENTO = "Magento",
  PWA_STUDIO = "PWA Studio",
  NEXT_JS = "NextJS",
  TALWIND = "Tailwind CSS",
  FIREBASE = "Firebase",
  GRAPHQL = "GraphQL",
  NEW_RELIC = "New Relic",
  GA = "Google Analytics",
  GTM = "Google Tag Manager",
  STORE_DEPLOY = "Apple Store and Google Play deployments",
  MICROSERVICES = "Microservices",
  REST = "RESTfull API",
  STYLED_COMPONENTS = "Styled Components",
  CI_CD = "CI/CD",
  NODE = "Node.js",
  REDUX = "Redux",
  JAVA = "Java",
  MOBX = "MobX",
}
